# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.core.validators
import django.db.models.deletion
import taletomo.planning.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arc_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('conflict_goal', models.TextField(blank=True, default='')),
                ('start_chapter', models.PositiveIntegerField()),
                ('end_chapter', models.PositiveIntegerField()),
                ('target_state_transition', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['arc_number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)])),
                ('title', models.CharField(default='', max_length=200)),
                ('pov_character_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('unplanned', 'Unplanned'), ('planned', 'Planned'), ('drafting', 'Drafting'), ('review', 'Under Review'), ('approved', 'Approved'), ('locked', 'Locked')], default='unplanned', max_length=20)),
                ('current_word_count', models.PositiveIntegerField(default=0)),
                ('current_summary', models.TextField(blank=True, default='')),
                ('active_draft_id', models.UUIDField(blank=True, null=True)),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='planning.arc')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ChapterPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('required_beats', models.JSONField(blank=True, default=list)),
                ('prohibited_outcomes', models.JSONField(blank=True, default=list)),
                ('continuity_requirements', models.JSONField(blank=True, default=list)),
                ('thread_operations', models.JSONField(blank=True, default=taletomo.planning.models.default_thread_operations)),
                ('end_state', models.JSONField(blank=True, default=list)),
                ('target_words', models.PositiveIntegerField(default=2200)),
                ('tolerance_percent', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('locked', 'Locked'), ('superseded', 'Superseded')], default='proposed', max_length=20)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='planning.chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('premise', models.TextField(help_text='Original hook or premise')),
                ('target_chapters', models.PositiveIntegerField(default=100, help_text='Target chapters from 1 through 4,000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)])),
                ('length_preset', models.CharField(choices=[('short', 'Short (800–1,500 words)'), ('standard', 'Standard (1,500–2,500 words)'), ('long', 'Long (2,500–4,000 words)'), ('custom', 'Custom (500–10,000 words)')], default='standard', max_length=20)),
                ('target_words_per_chapter', models.PositiveIntegerField(default=2200)),
                ('tolerance_percent', models.PositiveSmallIntegerField(default=15)),
                ('genre', models.CharField(default='Fantasy', max_length=100)),
                ('subgenre', models.CharField(blank=True, default='', max_length=100)),
                ('audience', models.CharField(default='Young Adult / General', max_length=100)),
                ('tone', models.CharField(default='Epic, Mysterious', max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('prose_language', models.CharField(default='English', max_length=50)),
                ('pov', models.CharField(default='Third Person Limited', max_length=50)),
                ('tense', models.CharField(default='Past Tense', max_length=30)),
                ('pacing', models.CharField(default='Balanced', max_length=50)),
                ('content_boundaries', models.TextField(blank=True, default='')),
                ('active_branch_head', models.CharField(default='rev_1', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='planning.project'),
        ),
        migrations.CreateModel(
            name='ScenePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_order', models.PositiveSmallIntegerField(default=1)),
                ('objective', models.CharField(max_length=300)),
                ('conflict', models.CharField(blank=True, default='', max_length=300)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('setting', models.CharField(blank=True, default='', max_length=200)),
                ('estimated_words', models.PositiveIntegerField(default=1000)),
                ('chapter_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='planning.chapterplan')),
            ],
            options={
                'ordering': ['scene_order'],
            },
        ),
        migrations.CreateModel(
            name='SeriesBible',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch', models.TextField(blank=True, default='')),
                ('hook', models.TextField(blank=True, default='')),
                ('central_conflict', models.TextField(blank=True, default='')),
                ('reader_promise', models.TextField(blank=True, default='')),
                ('world_setting', models.TextField(blank=True, default='')),
                ('era', models.CharField(blank=True, default='', max_length=100)),
                ('magic_tech_rules', models.JSONField(blank=True, default=list)),
                ('factions_overview', models.TextField(blank=True, default='')),
                ('tone_rules', models.JSONField(blank=True, default=list)),
                ('prose_style_guide', models.TextField(blank=True, default='')),
                ('author_constraints', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved')], default='approved', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bible', to='planning.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesSpine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_promise', models.TextField(blank=True, default='')),
                ('ending_direction', models.TextField(blank=True, default='')),
                ('major_milestones', models.JSONField(blank=True, default=list)),
                ('sparse_volumes_overview', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved')], default='approved', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spine', to='planning.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('premise', models.TextField(blank=True, default='')),
                ('target_chapters', models.PositiveIntegerField(default=50)),
                ('established_outcomes', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='planning.project')),
            ],
            options={
                'ordering': ['volume_number'],
                'unique_together': {('project', 'volume_number')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='planning.volume'),
        ),
        migrations.AddField(
            model_name='arc',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='planning.volume'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['project', 'chapter_number'], name='planning_ch_project_9193ce_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['project', 'status'], name='planning_ch_project_982516_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('project', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='arc',
            unique_together={('volume', 'arc_number')},
        ),
    ]
