# Generated by Django 5.1.15 on 2026-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='protagonist_type',
            field=models.CharField(blank=True, default='', help_text='Protagonist archetype (e.g. Underdog, Anti-hero) from the style dictionary', max_length=100),
        ),
    ]
