# Generated by Django 5.1.15 on 2026-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_project_protagonist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='novel_tags',
            field=models.CharField(blank=True, default='', help_text="NovelUpdates-style trope tags (e.g. 'Gender Bender, Reincarnation') from the style dictionary", max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='protagonist_type',
            field=models.CharField(blank=True, default='', help_text="Protagonist archetypes and traits (e.g. 'Trickster, Female Protagonist') from the style dictionary", max_length=200),
        ),
    ]
