# Generated by Django 5.1.15 on 2026-10-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_project_novel_tags_alter_project_protagonist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='branch_point_chapter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='planning.project'),
        ),
    ]
