# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(db_index=True, max_length=100)),
                ('target_id', models.CharField(db_index=True, max_length=100)),
                ('old_version', models.CharField(blank=True, default='', max_length=50)),
                ('new_version', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project_id', 'timestamp'], name='core_auditl_project_6f4fe2_idx'), models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx')],
            },
        ),
    ]
