# Generated by Django 5.1.15 on 2026-09-26 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('genre', 'Genre'), ('subgenre', 'Subgenre'), ('tone', 'Tone'), ('pov', 'Point of View'), ('tense', 'Narrative Tense'), ('pacing', 'Pacing')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Case-insensitive identity within the field', max_length=120)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True, default='')),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field', 'name'],
                'constraints': [models.UniqueConstraint(fields=('field', 'slug'), name='unique_style_term_per_field')],
            },
        ),
    ]
