# Generated by Django 5.1.15 on 2026-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_seed_protagonist_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleterm',
            name='field',
            field=models.CharField(choices=[('genre', 'Genre'), ('subgenre', 'Subgenre'), ('tone', 'Tone'), ('pov', 'Point of View'), ('tense', 'Narrative Tense'), ('pacing', 'Pacing'), ('protagonist', 'Protagonist Type')], db_index=True, max_length=20),
        ),
    ]
