# Generated by Django 5.1.15 on 2026-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_alter_styleterm_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleterm',
            name='field',
            field=models.CharField(choices=[('genre', 'Genre'), ('subgenre', 'Subgenre'), ('tone', 'Tone'), ('pov', 'Point of View'), ('tense', 'Narrative Tense'), ('pacing', 'Pacing'), ('protagonist', 'Protagonist Type'), ('protagonist_trait', 'Protagonist Trait'), ('tags', 'Novel Tags')], db_index=True, max_length=20),
        ),
    ]
