# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuityFinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_id', models.UUIDField(blank=True, null=True)),
                ('category', models.CharField(choices=[('identity', 'Identity & Naming'), ('injury', 'Injury & Status'), ('knowledge', 'Character Knowledge'), ('location', 'Location & Travel'), ('timeline', 'Timeline & Chronology'), ('rule', 'World Rule Violation'), ('plot', 'Plot Thread & Beat'), ('pov', 'POV & Tense Drift'), ('terminology', 'Terminology & Tone')], default='plot', max_length=30)),
                ('severity', models.CharField(choices=[('blocker', 'Blocker (Deterministic Contradiction)'), ('warning', 'Warning (Likely Continuity Issue)'), ('advisory', 'Advisory (Literary / Stylistic Note)')], default='warning', max_length=20)),
                ('confidence', models.FloatField(default=0.85)),
                ('claim', models.TextField(help_text='The contradictory claim detected in the prose')),
                ('conflicting_evidence', models.JSONField(default=list, help_text='References to canonical facts, rules, or character states that contradict the claim')),
                ('source_references', models.JSONField(default=list, help_text='Specific lines or scene locations in the draft')),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('intentional', 'Marked Intentional'), ('dismissed', 'Dismissed'), ('superseded', 'Superseded')], default='open', max_length=20)),
                ('override_rationale', models.TextField(blank=True, default='', help_text='Author explanation if marked intentional or dismissed')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_findings', to='planning.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_findings', to='planning.project')),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='consistency_project_6696d6_idx'), models.Index(fields=['chapter', 'severity'], name='consistency_chapter_880862_idx')],
            },
        ),
    ]
