# Generated by Django 5.1.15 on 2026-09-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consistency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuityfinding',
            name='category',
            field=models.CharField(choices=[('identity', 'Identity & Naming'), ('injury', 'Injury & Status'), ('knowledge', 'Character Knowledge'), ('location', 'Location & Travel'), ('timeline', 'Timeline & Chronology'), ('rule', 'World Rule Violation'), ('plot', 'Plot Thread & Beat'), ('pov', 'POV & Tense Drift'), ('terminology', 'Terminology & Tone'), ('length', 'Chapter Length')], default='plot', max_length=30),
        ),
    ]
