# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextManifest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_context_limit', models.PositiveIntegerField()),
                ('requested_output_tokens', models.PositiveIntegerField()),
                ('usable_budget', models.PositiveIntegerField()),
                ('category_budgets', models.JSONField(default=dict)),
                ('source_entries', models.JSONField(default=list, help_text='List of source items with id, version, priority, token_count, category, and hash')),
                ('total_assembled_tokens', models.PositiveIntegerField(default=0)),
                ('manifest_hash', models.CharField(db_index=True, max_length=64)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='planning.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='planning.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
