# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Provider', max_length=100)),
                ('provider_type', models.CharField(choices=[('fake', 'Fake / Mock Provider (Testing)'), ('openai_compatible', 'OpenAI Compatible Endpoint'), ('native', 'Native Provider')], default='fake', max_length=30)),
                ('endpoint_url', models.CharField(blank=True, default='https://api.openai.com/v1', help_text='Base URL for the provider endpoint', max_length=500)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('key_version', models.CharField(default='v1', max_length=20)),
                ('default_planning_model', models.CharField(default='mock-planning-v1', max_length=100)),
                ('default_drafting_model', models.CharField(default='mock-drafting-v1', max_length=100)),
                ('default_critique_model', models.CharField(default='mock-critique-v1', max_length=100)),
                ('model_profiles', models.JSONField(blank=True, default=dict, help_text='Verified or asserted model capabilities and pricing')),
                ('per_job_token_limit', models.PositiveIntegerField(default=128000)),
                ('daily_token_limit', models.PositiveIntegerField(default=1000000)),
                ('daily_cost_limit_usd', models.DecimalField(decimal_places=4, default=Decimal('20.0000'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('reserved_tokens', models.PositiveIntegerField()),
                ('reserved_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('confirmed_tokens', models.PositiveIntegerField(default=0)),
                ('confirmed_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('reconciled', 'Reconciled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id', 'status'], name='providers_b_project_f754be_idx'), models.Index(fields=['job_id'], name='providers_b_job_id_25089f_idx')],
            },
        ),
    ]
