# Generated by Django 5.1.15 on 2026-10-01 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='default_copilot_model',
            field=models.CharField(default='mock-copilot-v1', max_length=100),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='default_embedding_model',
            field=models.CharField(default='text-embedding-3-small', max_length=100),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='default_extraction_model',
            field=models.CharField(default='mock-extraction-v1', max_length=100),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='monthly_cost_limit_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('50.0000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='task_routing',
            field=models.JSONField(blank=True, default=dict, help_text='Task-to-model routing table'),
        ),
    ]
