# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('goals', models.TextField(blank=True, default='')),
                ('resources', models.TextField(blank=True, default='')),
                ('members', models.JSONField(blank=True, default=list)),
                ('alliances', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='planning.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlotThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('promise', 'Dramatic Promise'), ('mystery', 'Mystery / Clue'), ('debt', 'Personal Debt / Obligation'), ('deadline', 'Impending Deadline')], default='promise', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('progressing', 'Progressing'), ('resolved', 'Resolved'), ('abandoned', 'Abandoned')], default='open', max_length=30)),
                ('setup_chapter', models.PositiveIntegerField(default=1)),
                ('payoff_chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_threads', to='planning.project')),
            ],
            options={
                'ordering': ['setup_chapter', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StoryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='plot_progress', max_length=100)),
                ('summary', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_events', to='planning.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_events', to='planning.project')),
            ],
            options={
                'ordering': ['committed_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(db_index=True, max_length=50)),
                ('materialized_state', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='planning.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('story_time_valid_from', models.CharField(blank=True, default='', max_length=100)),
                ('story_time_valid_until', models.CharField(blank=True, default='', max_length=100)),
                ('real_order', models.PositiveIntegerField(default=1)),
                ('is_canon', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='planning.project')),
            ],
            options={
                'ordering': ['real_order'],
            },
        ),
        migrations.CreateModel(
            name='WorldRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('magic', 'Magic System'), ('tech', 'Technology / Science'), ('social', 'Social / Cultural'), ('physical', 'Physical / Environmental')], default='magic', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('rule_statement', models.TextField()),
                ('forbidden_violations', models.TextField(blank=True, default='', help_text='Explicitly prohibited outcomes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='planning.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanonFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(db_index=True, max_length=150)),
                ('predicate', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('truth_scope', models.CharField(choices=[('world_truth', 'World Truth (Objective)'), ('narrator_assertion', 'Narrator Assertion'), ('character_belief', 'Character Belief'), ('rumor', 'Rumor / Unconfirmed'), ('prophecy', 'Prophecy'), ('plan_only', 'Plan Only (Future Intent)'), ('author_note', 'Author Meta-Note'), ('noncanonical_draft', 'Noncanonical Draft Claim')], default='world_truth', max_length=40)),
                ('story_time_valid_from', models.CharField(blank=True, default='', max_length=100)),
                ('story_time_valid_until', models.CharField(blank=True, default='', max_length=100)),
                ('revision_valid_from', models.CharField(default='rev_1', max_length=50)),
                ('revision_valid_until', models.CharField(blank=True, default='', max_length=50)),
                ('provenance', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(default=1.0)),
                ('canonical_status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('deprecated', 'Deprecated')], default='confirmed', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canon_facts', to='planning.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'canonical_status'], name='canon_canon_project_c59830_idx'), models.Index(fields=['project', 'subject', 'predicate'], name='canon_canon_project_92a999_idx')],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('ally', 'Ally'), ('neutral', 'Neutral / Supporting')], default='neutral', max_length=30)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('goals', models.TextField(blank=True, default='')),
                ('internal_need', models.TextField(blank=True, default='')),
                ('wounds_status', models.TextField(blank=True, default='', help_text='Current physical wounds, injuries, or status impairments')),
                ('is_alive', models.BooleanField(default=True)),
                ('beliefs', models.JSONField(blank=True, default=list, help_text='What this character believes is true vs world truth')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='planning.project')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'name'], name='canon_chara_project_3f002b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('travel_rules', models.TextField(blank=True, default='')),
                ('current_state', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='planning.project')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'name'], name='canon_locat_project_9366e6_idx')],
            },
        ),
    ]
