# Generated by Django 5.1.15 on 2026-09-25 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0001_initial'),
        ('generation', '0002_alter_generationjob_status'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedCanonItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fact', 'Canon Fact'), ('event', 'Story Event'), ('thread_update', 'Plot Thread Update')], max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Structured proposal; shape depends on kind')),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('confidence', models.FloatField(default=0.8)),
                ('extracted_by_model', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('consumed', 'Consumed by Canon Commit')], default='proposed', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_canon_items', to='planning.chapter')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_canon_items', to='generation.draftartifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_canon_items', to='planning.project')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chapter', 'status'], name='canon_propo_chapter_2a74d0_idx'), models.Index(fields=['project', 'status'], name='canon_propo_project_04afdd_idx')],
            },
        ),
    ]
