# Generated by Django 5.1.15 on 2026-09-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0002_proposedcanonitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedcanonitem',
            name='kind',
            field=models.CharField(choices=[('fact', 'Canon Fact'), ('event', 'Story Event'), ('thread_update', 'Plot Thread Update'), ('character_update', 'Character Update')], max_length=20),
        ),
    ]
