# Generated by Django 5.1.15 on 2026-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0003_alter_proposedcanonitem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonfact',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='character',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storyevent',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
