# Generated by Django 5.1.15 on 2026-10-01 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0004_canonfact_embedding_character_embedding_and_more'),
        ('planning', '0003_project_novel_tags_alter_project_protagonist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coord_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='coord_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroyed_at_chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('status_notes', models.TextField(blank=True, default='')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_items', to='canon.character')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_items', to='canon.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.project')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'name'], name='canon_item_project_d75a85_idx')],
            },
        ),
    ]
