# Generated by Django 5.1.15 on 2026-10-01 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0005_location_coord_x_location_coord_y_location_region_and_more'),
        ('planning', '0004_project_branch_name_project_branch_point_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True, default='', help_text='Physical appearance, distinctive features, clothing, and presence'),
        ),
        migrations.AddField(
            model_name='character',
            name='dialogue_style',
            field=models.TextField(blank=True, default='', help_text='Speech patterns, vocabulary, dialect, cadence, and typical idioms'),
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(help_text='e.g. Rival, Mentor, Ally, Sibling, Romantic, Estranged, Debtor', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('dynamic_status', models.CharField(choices=[('friendly', 'Friendly / Cooperative'), ('hostile', 'Hostile / Antagonistic'), ('tense', 'Tense / Suspicious'), ('neutral', 'Neutral / Professional'), ('complex', 'Complex / Shifting')], default='neutral', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_relationships', to='planning.project')),
                ('source_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='canon.character')),
                ('target_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='canon.character')),
            ],
            options={
                'ordering': ['source_character__name', 'target_character__name'],
                'unique_together': {('source_character', 'target_character')},
            },
        ),
    ]
