# Generated by Django 5.1.15 on 2026-10-03 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canon', '0006_character_appearance_character_dialogue_style_and_more'),
        ('planning', '0004_project_branch_name_project_branch_point_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='plot_thread',
            field=models.ForeignKey(blank=True, help_text='Plot thread or mystery this artifact is tied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='canon.plotthread'),
        ),
        migrations.AddField(
            model_name='plotthread',
            name='dormancy_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Number of chapters before an unmentioned thread is flagged as dormant'),
        ),
        migrations.AddField(
            model_name='plotthread',
            name='last_mentioned_chapter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PlotThreadBreadcrumb',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('breadcrumb_type', models.CharField(choices=[('clue', 'Foreshadowing / Clue'), ('progression', 'Progress / Escalation'), ('twist', 'Revelation / Complication'), ('payoff', 'Climax / Payoff')], default='clue', max_length=30)),
                ('description', models.TextField()),
                ('is_discovered', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='canon.plotthread')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_breadcrumbs', to='planning.project')),
            ],
            options={
                'ordering': ['chapter_number', 'created_at'],
            },
        ),
    ]
