# Generated by Django 5.1.15 on 2026-09-22 15:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('prose_content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(default='', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('under_review', 'Under Review'), ('accepted', 'Accepted (Prose Approved)'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='planning.chapter')),
                ('context_manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='context.contextmanifest')),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='generation.draftartifact')),
            ],
            options={
                'ordering': ['chapter', '-version_number'],
                'unique_together': {('chapter', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='chapter_draft', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing_context', 'Preparing Context'), ('submitted', 'Submitted'), ('generating', 'Generating'), ('checking', 'Checking Continuity'), ('ready', 'Ready for Review'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('stale', 'Stale')], default='queued', max_length=30)),
                ('stage', models.CharField(default='queued', max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('confirmed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('confirmed_tokens', models.PositiveIntegerField(default=0)),
                ('lease_worker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('result_url', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('target_chapter_id', models.UUIDField(blank=True, null=True)),
                ('draft_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='generation.draftartifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='planning.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=150)),
                ('outcome', models.CharField(default='started', max_length=50)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='generation.generationjob')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['project', 'status'], name='generation__project_b966c9_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['idempotency_key'], name='generation__idempot_528914_idx'),
        ),
    ]
