# Generated by Django 5.1.15 on 2026-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preparing_context', 'Preparing Context'), ('submitted', 'Submitted'), ('generating', 'Generating'), ('checking', 'Checking Continuity'), ('extracting', 'Extracting Proposed Canon'), ('ready', 'Ready for Review'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('stale', 'Stale')], default='queued', max_length=30),
        ),
    ]
