# Generated by Django 5.1.15 on 2026-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('generation', '0002_alter_generationjob_status'),
        ('planning', '0004_project_branch_name_project_branch_point_chapter_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='draftartifact',
            index=models.Index(fields=['chapter', 'version_number'], name='generation__chapter_927fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='draftartifact',
            index=models.Index(fields=['chapter', 'status'], name='generation__chapter_9bb3b6_idx'),
        ),
    ]
